# Generated by Django 5.1.3 on 2024-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_food_delete_user_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='img',
            new_name='image',
        ),
    ]
